export const SET_LOADING = 'SET_LOADING'
export const SET_SUCCESS = 'SET_SUCCESS'
export const SET_FAILED = 'SET_FAILED'

export const SET_NAVIGATE = 'SET_NAVIGATE'
export const SET_ACTIVE_PAGE_HOME = 'SET_ACTIVE_PAGE_HOME'

export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'

export const SAVE_SESSION_FOR_PERSISTANCE = 'SAVE_SESSION_FOR_PERSISTANCE'

export const FETCH_REGIONALS_SUCCESS = 'FETCH_REGIONALS_SUCCESS'

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_SUBPRODUCTS_SUCCESS = 'FETCH_SUBPRODUCTS_SUCCESS'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'

export const FILTER_CUSTOMERS_WITH_ID = 'FILTER_CUSTOMERS_WITH_ID'

export const GET_USER_NATION_RANK = 'GET_USER_NATION_RANK'
export const GET_USER_REGION_RANK = 'GET_USER_REGION_RANK'

export const FETCH_PIPELINES_SUCCESS = 'FETCH_PIPELINES_SUCCESS'

export const RECEIVE_CUSTOMER_PLACES = 'RECEIVE_CUSTOMER_PLACES'
export const SELECTED_CUSTOMER_PLACE = 'SELECTED_CUSTOMER_PLACE'

export const INPUT_DATA_TO_CUSTOMER = 'INPUT_DATA_TO_CUSTOMER'

export const RECEIVE_PICS_SUCCESS = 'RECEIVE_PICS_SUCCESS'

export const CHECK_CUSTOMER = 'CHECK_CUSTOMER'

export const ADD_PIC = 'ADD_PIC'
export const REMOVE_PIC = 'REMOVE_PIC'

export const PICS_CUSTOMERS = 'PICS_CUSTOMERS'

export const FETCH_PICS_SUCCESS = 'FETCH_PICS_SUCCESS'

export const FETCH_PIPELINES_WITH_USER_ID_SUCCESS = 'FETCH_PIPELINES_WITH_USER_ID_SUCCESS'
export const FETCH_QUESTION_WITH_STEP_SUCCESS = 'FETCH_QUESTION_WITH_STEP_SUCCESS'