export const SET_LOADING = 'SET_LOADING'
export const SET_FAILED = 'SET_FAILED'
export const SET_NAVIGATE = 'SET_NAVIGATE'
export const SET_ACTIVE_PAGE_HOME = 'SET_ACTIVE_PAGE_HOME'

export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'

export const SAVE_SESSION_FOR_PERSISTANCE = 'SAVE_SESSION_FOR_PERSISTANCE'

export const FETCH_REGIONALS_SUCCESS = 'FETCH_REGIONALS_SUCCESS'

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_SUBPRODUCTS_SUCCESS = 'FETCH_SUBPRODUCTS_SUCCESS'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'

export const FILTER_CUSTOMERS_WITH_ID = 'FILTER_CUSTOMERS_WITH_ID'

export const GET_USER_NATION_RANK = 'GET_USER_NATION_RANK'
export const GET_USER_REGION_RANK = 'GET_USER_REGION_RANK'

export const FETCH_PIPELINES_SUCCESS = 'FETCH_PIPELINES_SUCCESS'